### ISSUE TITLE
Thunderbird 68 compatibility

### ISSUE THREAD

**Issue by tigers75** [peci1/more-snooze#1]
Hi, I noticed the extension is not compatible with TB 68. It probably the most useful extension I use with LIghtning, so it definitely worth upgrading.
Thanks.

**Comment by peci1** [comment]
Hi, I planned to convert this addon to webextensions API, but haven't got to that yet. I'm not even sure if it is possible with the new API. 

I definitely want to look into that, however, I don't know, when I'll have time to do it. Any help welcome :)

**Comment by jameshibbard** [comment]
Hi, I'll take this.

**Comment by jameshibbard** [comment]
Hi, 

I had a look into what it would take to upgrade the extension to TB68 and beyond.

> I planned to convert this addon to webextensions API

AFAIK, this is not possible. From [here](https://extensionworkshop.com/documentation/develop/comparison-with-xul-xpcom-extensions/#ui):

> XUL extensions can build their UI by directly manipulating the XUL used to specify the browser’s own UI. ... They can not only add any elements to the browser’s UI, they can also modify or remove existing elements. Extensions built with WebExtension APIs don’t get this kind of direct access. Instead, a combination of manifest.json keys and JavaScript APIs enable them to add a limited set of UI components to the browser.

Given that and the fact that TB68 includes a new XUL overlay loader (which allows overlay extensions to continue working for the time being), it seems that the most sensible path would be keep More Snooze as an overlay extension.

> the extension is not compatible with TB 68

The biggest reason for this is the fact that More Snooze uses XBL to extend the calendar snooze dialog. Unfortunately, XBL is on death row and support will soon be removed altogether. It would probably make most sense to use (a) custom element(s) for this purpose.

@peci1: what do you think? Does this approach sound ok? I'd be interested in helping you update the extension if this is something you think is worthwhile.

**Comment by peci1** [comment]
I still haven't got time to dive into the new webextensions apis, so if you wanna take this path, go on. If I understand it correctly, making MoreSnooze an overlay "webextension" is only a temporary solution? 

Maybe, while this still works, we could try to talk to Lightning people to expose an API, or even better a config for what MoreSnooze does... MoreSnooze could then just become a GUI for a configuration option of Lightning...

**Comment by jameshibbard** [comment]
> making MoreSnooze an overlay "webextension" is only a temporary solution

Yeah man, temporary. I'm not even 100% sure that it would work, but it seems the easiest option to explore given the changes going on with Thunderbird right now.

> if you wanna take this path, go on

Ok cool. I don't want to promise too much, as I am also rather busy with day job etc, but I'll make a start. Would it be ok to contact you on the email associated with this GiutHub profile if I have any questions?

> MoreSnooze could then just become a GUI for a configuration option of Lightning...

That sounds like the best plan long term :)

**Comment by peci1** [comment]
@jameshibbard Let's talk on https://gitter.im/more-snooze .

**Comment by peci1** [comment]
In the meantime, I've asked Lightning developers if they could make the snooze presets configurable, which would render this addon useless.

https://bugzilla.mozilla.org/show_bug.cgi?id=1589271

**Comment by peci1** [comment]
The updated version is on master now. Many thanks to @jameshibbard without whose help this would have taken much longer! You can expect the new version to be released to the official addons site in a few days.
