### ISSUE TITLE
Not compatible with TB 128

### ISSUE THREAD

**Issue by PeterMacej** [peci1/more-snooze#12]
This great addon is disabled in TB 128.

**Comment by peci1** [comment]
I'll have a look at it tonight.

**Comment by peci1** [comment]
A compatible version 3.3.3 has been submitted to ATN and should arrive as auto update in a few days.

For the impatient, it can also be downloaded from https://github.com/peci1/more-snooze/releases/tag/v3.3.3 .

**Comment by peci1** [comment]
The new version has just been released on the official addons site.
