### ISSUE TITLE
Thunderbird 78 compatibility

### ISSUE THREAD

**Issue by dennis-grunert** [peci1/more-snooze#5]
Unfortunately, this addon is shown as not compatible with Thunderbird 78.4.0 and was deactivated by Thunderbird.

**Comment by peci1** [comment]
Working on it ;)

**Comment by antoniomorais360** [comment]
Hello. Not working in 78.10.1 version .. :) Love to use it again.

**Comment by peci1** [comment]
There is an alpha version for TB 78+:  
[moresnooze@cyrille.nocus.zip](https://github.com/peci1/more-snooze/files/6587492/moresnooze%40cyrille.nocus.zip) (just download, change extension from .zip to .xpi and drag'n'drop to the addons page in TB)

The preferences window is not yet working, so do not try to change anything there (the window shows, but it's unclear what will it do, so rather do not touch it). But if you were satisfied with your settings, then this alpha version should successfully import them and work.

**Comment by antoniomorais360** [comment]
Hello @peci1 I just upload and activate more snooze um my tb 78+ but nothing happens. It shows the same options like before, but there is no error in uploading/activating addon. Tks

**Comment by peci1** [comment]
Oh, I'm sorry, I uploaded an older version. Try this one: 
[more-snooze-tb78.zip](https://github.com/peci1/more-snooze/files/6591409/more-snooze-tb78.zip)

Let me know if it helped.

**Comment by ArminJo** [comment]
more-snooze-tb78.zip corrupts the default settings 😭
![2021-06-03 15_12_44-Kalender - Mozilla Thunderbird](https://user-images.githubusercontent.com/3881884/120650559-32ac2d00-c47e-11eb-9bf4-4005bebbccdd.png)

After installation there are only the 4 selections 
![2021-06-03 14_46_38-Add-ons-Verwaltung - Mozilla Thunderbird](https://user-images.githubusercontent.com/3881884/120649421-08a63b00-c47d-11eb-8b09-12b2182eb013.png)
of _Standardwerte_ available regardless what one select!
![2021-06-03 15_00_18-Kalender - Mozilla Thunderbird](https://user-images.githubusercontent.com/3881884/120649330-ec0a0300-c47c-11eb-8a50-870bcf2abd29.png)

I had to uninstall it to restore to the default selection 😞

**Comment by peci1** [comment]
I've told that the preferences window does not work yet. The fact you remain with just 4 options is weird, though.

There is a way to change the settings, though. Open the addons page, click the cog wheel in top right, click Debug addons. Find MoreSnooze and click the button to the right ("explore" or something like that). This opens a page with the addon debugging options. In the left part, expand "Addon data storage" and click the "moz-extension...". In the right part, you'll see the preferences. Just type `true` to the options you want.

![Snímek z 2021-06-03 15-49-58](https://user-images.githubusercontent.com/182533/120655940-75243880-c483-11eb-9725-e06881b8fc5d.png)

**Comment by ArminJo** [comment]
The method above  works for me until the next start of Thunderbird 😭

**Comment by peci1** [comment]
Hmm, I've just installed the addon to a computer where TB got updated yesterday and this method works for me even after a restart... I'm not sure what's happening in your case. How did you install the addon? Drag'n'drop of the downloaded XPI to the addons page?

**Comment by ArminJo** [comment]
I updated my Thunderbird 78.11.0 (32bit) a hour ago and installed the addon with "Add-on administration" >  "install addon from file" using the renamed more-snooze-tb78.zip.

**Comment by peci1** [comment]
Hmm, I'm clueless here... Maybe try:

1. install addon
2. restart TB
3. change settings

Will that help?

**Comment by ArminJo** [comment]
> Will that help?

No!

**Comment by ArminJo** [comment]
Even not with the 64 bit version.

**Comment by peci1** [comment]
That's all I could figure out, so you probably have to wait until a properly working version is released. No time estimate for that, though...

**Comment by peci1** [comment]
Good news! I had a free evening and it seems I've got the preferences working. Give it a try! 
[moresnooze@cyrille.zip](https://github.com/peci1/more-snooze/files/6603366/moresnooze%40cyrille.zip)

**Comment by ArminJo** [comment]
Martin you are a genius 💯.
Thanks for your effort!
I now works like a charm!

**Comment by peci1** [comment]
This issue has been resolved, version 3.0.0 is pending review on addons.thunderbird.net.

**Comment by sphh** [comment]
@peci1: I use it on TB 78 and it works perfectly. Thanks!

But I miss the update on addons.thunderbird.net. Is this still in review (does it really take that long to review an add-on?) or are there any other problem with the review, so that it has not appeared yet on the add-ons page?

**Comment by peci1** [comment]
I got some comments requiring more changes in the addon review. But the requested changes are too large for me to make (and understand) them. The reviewer told he will help with them, but radio silence since then...

**Comment by sphh** [comment]
O, that's a pity!

I really hope, that s/he'll get into contact with you to help!!

**Comment by peci1** [comment]
It's actually my error, I didn't notice mozilla chat doesn't send email notifications, so the reviewer responded to me, but I didn't notice

**Comment by JohnAnderson** [comment]
Works for me in TB 78.13.0!  Thanks!

Hope it becomes "official" soon.

**Comment by skrevier** [comment]
Thanks for all this Martin!!

**Comment by peci1** [comment]
The official release for TB 78 and 91 is here! You can update it via addons manager now.

**Comment by georg-d** [comment]
As this is resolved, the hint

> For compatibility with TB 78+ see https://github.com/peci1/more-snooze/issues/5 .

on https://addons.thunderbird.net/en-US/thunderbird/addon/more-snooze/?src=cb-dl-popular can probably be removed 🙂

**Comment by peci1** [comment]
Done, thanks for the hint.
