### ISSUE TITLE
Please upgrade to Lightning 91.3.0

### ISSUE THREAD

**Issue by zounp** [peci1/more-snooze#8]
Hello Cyrille Nocus and Peci1,
Thanks for More-snooze. I like it a lot.
Currently it works with Thunderbird 78.0 - 91.*
It would be nice if you could keep the app working.
Thanks.
Regards, Zounp

**Comment by peci1** [comment]
Hi, I'm sorry, but I don't have energy for keeping up with development releases of Thunderbird. The only thing I told myself I'll try is keeping up with stable releases (currently 91.*).

If you want the addon working in test releases, it will need your (or anybody else's) help.

**Comment by zounp** [comment]
Hello peci1,
Not so nice you having an energy issue. I hope it is not to bad.
Aha, Somehow I must have updated to the beta channel and work with beta version 95. I reverted back to the release update channel and are now on version 91.3.0
If I am right that is what you mean with stable releases.
In version 91.3.0 I get "MoreSnooze is incompatible with Thunderbird 91.3.0."
So I thougth it needed to be updated. However it seemed that I had to update. Confusing. So I did update. That resolved the issue.
It is working as expected now :-)
Thanks for MoreSnooze. It makes working with Lightning much more pleasant.

**Comment by jameshibbard** [comment]
>  In version 91.3.0 I get "MoreSnooze is incompatible with Thunderbird 91.3.0."

Really? I just tested it out and it works as expected for me (TB 91.3.0, Linux).
I tried installing via the addons site, as well as cloning the repo (branch tb78) and loading the extension as a temporary addon.

**Edit**: ah ok, I see you updated your previous post. All good :+1:
